---
title: "Conditional Expectation Functions"
author: "D. Alex Hughes"
date: "4/25/2020"
output: github_document
---

# Section 1 

This is some text. That. 

```{r load packages}
library(dplyr)
library(plotly)
```

```{r make data}
d <- data.frame(
  id = 1:5000
)

d <- d %>% 
  mutate(
    x = runif(n = n(), min = 0, max = 4*pi), 
    y = runif(n = n(), min = 0, max = 4*pi)
  ) %>%  
  mutate(
    z = pnorm(0 + .5 * x + sin(x) + sin(y))
  )
```

```{r}
fig <- plot_ly(
  data = d, 
  x = ~x, y = ~y, z = ~z) %>%  
  add_markers(
    size = 1,
    color = I('grey40')
  ) %>%  
  layout(
    title = 'Probability of Retaining Customer',   
    scene = list(
      xaxis = list(title = 'Years'),
      yaxis = list(title = 'Purchases'),
      zaxis = list(title = 'P(Return)')
    )
  )
fig
```





```{r make data}
d <- data.frame(
  id = 1:500
)

d <- d %>% 
  mutate(
    x = runif(n = n(), min = 0, max = 4*pi), 
    y = runif(n = n(), min = 0, max = 4*pi)
  ) %>%  
  mutate(
    z = pnorm(0 + .5 * x + sin(x) + sin(y))
  )
```

```{r}
fig <- plot_ly(
  data = d, 
  x = ~x, y = ~y, z = ~z) %>%  
  add_markers(
    size = 1,
    color = I('grey40')
  ) %>%  
  layout(
    title = 'Probability of Retaining Customer',   
    scene = list(
      xaxis = list(title = 'Years'),
      yaxis = list(title = 'Purchases'),
      zaxis = list(title = 'P(Return)')
    )
  )
fig
```